# coding: utf-8

"""
Matchmaking and Notification Service API

This file defines the FastAPI application entrypoint.
Routers generated by OpenAPI Generator are included.
We also add custom endpoints (like /db-test-c) here.

Do NOT remove generated router includes unless you 
intentionally want to disable API sections.
"""

from fastapi import FastAPI

# Import the generated API router
from openapi_server.apis.default_api import router as DefaultApiRouter

# Import your database connection helper
from openapi_server.impl.db import get_connection


# ===============================================================
# 1. Create the FastAPI application instance
# ===============================================================
app = FastAPI(
    title="Matchmaking and Notification Service API",
    description=(
        "API-first definition for the Matchmaking and Notification microservice. "
        "Each resource (matches, offers, health) includes GET, POST, PUT, "
        "and DELETE methods. These endpoints were generated from OpenAPI."
    ),
    version="1.0.0",
)


# ===============================================================
# 2. Register the auto-generated API routes
#    (matches, offers, health, etc.)
# ===============================================================
app.include_router(DefaultApiRouter)


# ===============================================================
# 3. Custom endpoint to verify Cloud SQL connectivity
#    This is NOT part of the generated API. It is custom logic.
# ===============================================================
@app.get("/db-test-c")
def db_test_c():
    """
    Simple endpoint used ONLY to test DB connectivity.
    Returns the name of the currently selected MySQL database.
    """
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT DATABASE()")
    row = cur.fetchone()

    cur.close()
    conn.close()

    return {"connected_to": row[0]}
