# coding: utf-8

"""
Matchmaking and Notification Service API

This file defines the FastAPI application entrypoint.
Routers generated by OpenAPI Generator are included.
We also add custom endpoints (like /db-test-c) here.

Do NOT remove generated router includes unless you 
intentionally want to disable API sections.
"""

from fastapi import FastAPI
from openapi_server.apis.default_api import router as DefaultApiRouter

# Internal DB
from openapi_server.impl.db import get_connection

# Donor Registry (MS1) Client
from openapi_server.impl.donor_registry_client import (
    get_health,
    list_donors,
    get_donor,
    list_organs_for_donor,
    list_organs,
    list_consents,
    get_consent,
)

# ===============================================================
# 1. Create FastAPI application instance
# ===============================================================
app = FastAPI(
    title="Matchmaking and Notification Service API",
    description=(
        "API-first definition for the Matchmaking and Notification microservice. "
        "Each resource (matches, offers, health) includes GET, POST, PUT, "
        "and DELETE methods. These endpoints were generated from OpenAPI."
    ),
    version="1.0.0",
)

# ===============================================================
# 2. Register OpenAPI-generated routes
# ===============================================================
app.include_router(DefaultApiRouter)


# ===============================================================
# 3. INTERNAL: DB TEST ENDPOINT
# ===============================================================
@app.get("/db-test-c")
def db_test_c():
    """Test connection to Cloud SQL."""
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT DATABASE()")
    row = cur.fetchone()
    cur.close()
    conn.close()
    return {"connected_to": row[0]}


# ===============================================================
# 4. MS1: Donor Registry Service Endpoints
# ===============================================================

# --- Health ---
@app.get("/ms1/health")
def ms1_health():
    """Check health of MS1."""
    return get_health()


# --- Donors ---
@app.get("/ms1/donors")
def ms1_list_donors():
    return list_donors()


@app.get("/ms1/donors/{donor_id}")
def ms1_get_donor(donor_id: str):
    return get_donor(donor_id)


@app.get("/ms1/donors/{donor_id}/organs")
def ms1_organs_for_donor(donor_id: str):
    return list_organs_for_donor(donor_id)


# --- Organs ---
@app.get("/ms1/organs")
def ms1_list_organs():
    return list_organs()


# --- Consents ---
@app.get("/ms1/consents")
def ms1_list_consents():
    return list_consents()


@app.get("/ms1/consents/{consent_id}")
def ms1_get_consent(consent_id: str):
    return get_consent(consent_id)


# --- Fetch ALL data from MS1 ---
@app.get("/ms1/all")
def ms1_all():
    """Convenience endpoint to fetch donors, organs, and consents."""
    return {
        "donors": list_donors(),
        "organs": list_organs(),
        "consents": list_consents(),
    }
