# coding: utf-8

"""
    Matchmaking and Notification Service API

    API-first definition for the Matchmaking and Notification microservice. Each resource (matches, offers, health) includes GET, POST, PUT, and DELETE methods. These endpoints are defined for design purposes only — no implementation is required. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Matchmaking and Notification Service API",
    description="API-first definition for the Matchmaking and Notification microservice. Each resource (matches, offers, health) includes GET, POST, PUT, and DELETE methods. These endpoints are defined for design purposes only — no implementation is required. ",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
