# coding: utf-8

"""
    Matchmaking and Notification Service API

    API-first definition for the Matchmaking and Notification microservice. 
    Each resource (matches, offers, health) includes GET, POST, PUT, and DELETE methods. 
    These endpoints are defined for design purposes only — no implementation is required. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import json
from pydantic import BaseModel, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class Offer(BaseModel):
    """
    Offer
    Represents an allocation offer generated from a match.
    Tracks its delivery and acceptance lifecycle.
    """  # noqa: E501

    id: Optional[StrictStr] = None
    match_id: StrictStr = Field(alias="matchId")
    recipient_id: Optional[StrictStr] = Field(None, alias="recipientId")
    status: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = Field(None, alias="createdAt")
    updated_at: Optional[StrictStr] = Field(None, alias="updatedAt")

    __properties: ClassVar[List[str]] = [
        "id",
        "matchId",
        "recipientId",
        "status",
        "createdAt",
        "updatedAt",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value
        if value not in ("pending", "accepted", "declined", "expired"):
            raise ValueError(
                "must be one of enum values ('pending', 'accepted', 'declined', 'expired')"
            )
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Offer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        Differences from pydantic's `self.model_dump(by_alias=True)`:
        * `None` values are only added if explicitly set.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Offer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "matchId": obj.get("matchId"),
                "recipientId": obj.get("recipientId"),
                "status": obj.get("status"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
            }
        )
        return _obj
